version: 0.2

phases:
  build:
    commands:
      - export IP_ADDRESS=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=sprint6-cr" --query "Reservations[].Instances[].PublicIpAddress" --output text)

artifacts:
  files:
    - appspec.yml
    - buildspec.yml
    - index.html
    - scripts/install_dependencies
    - scripts/start_server
    - scripts/stop_server
